plot:
  sizeX: 32  sizeY: 256
  sizeZ: 32  offsetX: 0  offsetY: 0  offsetZ: 0  multiplier: 1  maxPerPlayer: 1  initial: 1
  floor:
    generate: true
    clearSpaceAbove: 66
    material: GRASS
    supports:
      generate: true
      material: STONE
  sign:
    generate: true
road:
  width: 4
  clearSpaceAbove: 66
  level: 62
  material: COBBLESTONE
  supports:
    generate: true
    material: STONE
spawn:
  generate: true
  setAsWorldSpawn: true
  material: GRASS
wall:
  generate: true
  material: BEDROCK
  height: 66
worldname: world
userOverrides:
- username: majinnaibu
  plotMultiplier: 2
  maxPlots: 2
- username: hoggrim
  plotMultiplier: 2
  maxPlots: 2
