name: Metropolis
main: com.majinnaibu.bukkit.plugins.metropolis.MetropolisPlugin
depend: [WorldEdit, WorldGuard]
version: 0.4.1
database: false
commands:
  metropolis-home-generate:
    description: This command generates a home for a user as if they'd just logged in.
    permission: metropolis.generate
    usage: /metropolis-home-generate <playername>
  metropolis-home-list:
    description: This lists the regions managed by Metropolis
    permission: metropolis.list
    usage: /metropolis-home-list