plot:
  sizeX: 24
  sizeZ: 24
  floor:
    generate: true
    material: 2
  sign:
    generate: true
road:
  width: 4
  clearSpaceAbove: 66
  level: 62
  material: 4
spawn:
  generate: true
  setAsWorldSpawn: true
  material: 2
worldname: world
