plot:
  sizeX: 24
  sizeZ: 24
  floor:
    generate: true
    clearSpaceAbove: 66
    material: 2
    supports:
      generate: true
      material: 1
  sign:
    generate: true
road:
  width: 4
  clearSpaceAbove: 66
  level: 62
  material: 4
  supports:
    generate: true
    material: 1
spawn:
  generate: true
  setAsWorldSpawn: true
  material: 2
wall:
  generate: true
  material: 7
  height: 66
worldname: world
