plot:
  sizeX: 32   sizeY: 256
  sizeZ: 32   ovvsetX: 0   offsetY: 0   offsetZ: 0   defaultMultiplier: 1   maxPerPlayer: 1   initial: 1
  floor:
    generate: true
    clearSpaceAbove: 66
    material: 2
    supports:
      generate: true
      material: 1
  sign:
    generate: true   userOverrides:   	- username: majinnaibu   	  plotMultiplier: 2   	  maxPlots: 2   	- username: hoggrim   	  plotMultiplier: 2   	  maxPlots: 2
road:
  width: 4
  clearSpaceAbove: 66
  level: 62
  material: 4
  supports:
    generate: true
    material: 1
spawn:
  generate: true
  setAsWorldSpawn: true
  material: 2
wall:
  generate: true
  material: 7
  height: 66
worldname: world
